services:
  - type: web
    name: destiny-store
    env: docker
    plan: free
    repo: https://github.com/FabricioNunez/Destiny_store
    branch: main
    rootDir: .
    buildFilter:
      paths:
        - Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
